name: Run Python Script

# Set the schedule using cron
on:
  schedule:
    - cron: '*/15 * * * *'  # This runs the job every 15M day at 6 AM UTC. Adjust as needed.
  workflow_dispatch: # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'  # You can specify the Python version you need

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # If you have a requirements.txt file for dependencies
          
      # Step 4: Run the Python script
      - name: Run Python script
        run: |
          python HMM_DMI.py
